### ISSUE TITLE
ディレクトリ名の CamelCase をやめたい

### ISSUE THREAD

**Issue by meltingrabbit** [arkedge/c2a-core#10]
## 詳細
- https://github.com/arkedge/c2a-core/issues/7#issuecomment-1641294759 ででた
  - `これはファイル名・ディレクトリ名で大文字か小文字かにあまり意味を持たせたくない（し、Win だとこれは実際機能してなかった）半分、Rust の慣習に寄せたい半分です。`
- 影響範囲が大きいので，精査してやる

## close条件
できたら

**Comment by meltingrabbit** [comment]
- https://github.com/arkedge/c2a-core/issues/8 の前にやらないと死にそう

**Comment by sksat** [comment]
正確には，snake_case にしたいというよりは現状の機能していないことすらある中途半端な CamelCase をやめたい

**Comment by sksat** [comment]
> * [C2A 用語のリネーム #8](https://github.com/arkedge/c2a-core/issues/8) の前にやらないと死にそう

これは別に同時にやればよいし，その方がよい

**Comment by sksat** [comment]
@meltingrabbit #8 とも関連しますが，`TlmCmd` って素朴に `tlm_cmd` にしますか？それとも `tlmcmd` という1語ということにしますか？（どうせ略語なのであまり区切る意味がない + https://github.com/arkedge/c2a-tlmcmddb/ とかとの整合）

**Comment by meltingrabbit** [comment]
これわからんな．．．．ちょっと F' とか kubos とかどうなってるか調べてほしい @sksat

**Comment by sksat** [comment]
他がどうなってるかというよりは C2A というエコシステムの中でどうするかという決めの問題だと思ってます

**Comment by meltingrabbit** [comment]
宇宙業界で一般的なほうに寄せたほうが良くないですか？
日本語でいう「テレコマ」に相当する英語がどうなってるか，だと思ってます．

**Comment by meltingrabbit** [comment]
まあ，C2A上ではtlmとcmdは区別されてるので，C2Aエコシステムでは，であれば `tlm_cmd` かな．

**Comment by meltingrabbit** [comment]
F' は tlm と cmd でフォルダ別れてる．．．

`tlm_cmd` で行きましょう．

**Comment by meltingrabbit** [comment]
CTCP; common tlm cmd packet などもあるから，分ける，で確定で．

**Comment by sksat** [comment]
本当は tlm と cmd と共通部分（CTCP）でそれぞれ区切りたいやつでしょうねえ。ここでは一旦 tlm_cmd でよさそう
