### ISSUE TITLE
pytest CI を入れる

### ISSUE THREAD

**Issue by meltingrabbit** [arkedge/c2a-core#12]
## 詳細
- AE internal で動いてるもの

## close条件
いれたら

**Comment by meltingrabbit** [comment]
@sksat これお願いしたい．
AE GS SW が OSS になるまえでも，入れられたりするっけ？ or OSS 化をまたないとだめ？

**Comment by sksat** [comment]
基本的には OSS 化 required です（なので同じ文脈で各所で言及してます）

**Comment by meltingrabbit** [comment]
OK

**Comment by sksat** [comment]
#60 でやった
