### ISSUE TITLE
CCSDS周りのコードをcoreで管理する？

### ISSUE THREAD

**Issue by meltingrabbit** [arkedge/c2a-core#196]
## 詳細
汎用性が高い / user ごとのメンテがだるいので，core に持ちたい
ただし，CCSDSの様々なオプションを具備するのはだるいので，考える必要はある
ひとまずは現状のexampleのものをcoreに配置するか？

## close条件
coreに移植したら

## 議論
- https://github.com/ut-issl/c2a-core/issues/51 のつづき

**Comment by sksat** [comment]
ビルドオプションを用意してスイッチすることはよいと思います．でも名前と置き場はちょっと考えたいですね．ビルドオプションの違いだけだとファイルの特性の違いが非自明なので．
ソースファイルに `mobc_` みたいな prefix 付けるとか，ディレクトリ切るとか．

**Comment by meltingrabbit** [comment]
ファイル名にprefixつけるのは，構造体名との一致が取れなくなってちょっと嫌なので，

> ディレクトリ切るとか

でいきたいな
core/tlm_cmd/ccsds/mobc

みたいな形で突っ込みます．
PRつくったら cmakeまわりの整備頼んでもいいですか？

**Comment by sksat** [comment]
了解です．ではディレクトリ分割の方向で．
