### ISSUE TITLE
C2A HAL のもうつかわないだろう，というファイルを消す

### ISSUE THREAD

**Issue by meltingrabbit** [arkedge/c2a-core#23]
## 詳細
- [x] https://github.com/arkedge/c2a-core/blob/develop/IfWrapper/aa.h: #129 
- [x] https://github.com/arkedge/c2a-core/blob/develop/IfWrapper/dc.h: #25 
  - 使われてしまってるので，GPIOにしていく作業をきちんとやる必要あり 
- [x] https://github.com/arkedge/c2a-core/blob/develop/IfWrapper/pa.h: #130 
- [x] https://github.com/arkedge/c2a-core/blob/develop/IfWrapper/spwire.h: #131 
  - 使う可能性ありそうだけどサポートめんどいので一旦消して良さそう

## close条件
けしたら

**Comment by sksat** [comment]
`DC` については v4 で消す．理由は以下．

- 名前が伝わらなさすぎる
- 既に使われてしまってはいるが，一部の C2A user に限られている
  - また，それ以外の C2A user では独自に GPIO のインターフェース定義が行われている
  - ↑ こちらの方が DriverSuper に乗っていない素直な実装なので，c2a-core に置くとしたらこれに置き換えたい
- これを一旦 c2a-core に残してリファクタするよりも，一度消してやり直す方が整理として適切
  - GPIO は DriverSuper の仕組みに乗っているべきではないので，段階的な移行を試みてもほぼ書き換えにしかならない
  - 当然 breaking change になるが，使っている C2A user も一旦ヘッダを user 側に置けば延命可能
